<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Correlativa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Correlativa_model');
    } 

    /*
     * Listing of correlativas
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('correlativa/index?');
        $config['total_rows'] = $this->Correlativa_model->get_all_correlativas_count();
        $config['attributes'] = array('class' => 'page-link');
        $this->pagination->initialize($config);

        $data['correlativas'] = $this->Correlativa_model->get_all_correlativas($params);
        
        $data['_view'] = 'abm/correlativa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new correlativa
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_ciclo_materia','Id Ciclo Materia','required');
		$this->form_validation->set_rules('id_correlativa','Id Correlativa','required');
		$this->form_validation->set_rules('id_correlativa_tipo','Id Correlativa Tipo','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_ciclo_materia' => $this->input->post('id_ciclo_materia'),
				'id_correlativa' => $this->input->post('id_correlativa'),
				'id_correlativa_tipo' => $this->input->post('id_correlativa_tipo'),
            );
            
            $correlativa_id = $this->Correlativa_model->add_correlativa($params);
            redirect('correlativa/index');
        }
        else
        {
			$this->load->model('Ciclo_materia_model');
			$data['all_ciclo_materia'] = $this->Ciclo_materia_model->get_all_ciclo_materia();
			$data['all_correlativas'] = $this->Correlativa_model->get_all_correlativas();

			$this->load->model('Correlativas_tipo_model');
			$data['all_correlativas_tipo'] = $this->Correlativas_tipo_model->get_all_correlativas_tipo();
            
            $data['_view'] = 'abm/correlativa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a correlativa
     */
    function edit($id)
    {   
        // check if the correlativa exists before trying to edit it
        $data['correlativa'] = $this->Correlativa_model->get_correlativa($id);
        
        if(isset($data['correlativa']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_ciclo_materia','Id Ciclo Materia','required');
			$this->form_validation->set_rules('id_correlativa','Id Correlativa','required');
			$this->form_validation->set_rules('id_correlativa_tipo','Id Correlativa Tipo','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_ciclo_materia' => $this->input->post('id_ciclo_materia'),
					'id_correlativa' => $this->input->post('id_correlativa'),
					'id_correlativa_tipo' => $this->input->post('id_correlativa_tipo'),
                );

                $this->Correlativa_model->update_correlativa($id,$params);            
                redirect('correlativa/index');
            }
            else
            {
				$this->load->model('Ciclo_materia_model');
				$data['all_ciclo_materia'] = $this->Ciclo_materia_model->get_all_ciclo_materia();
				$data['all_correlativas'] = $this->Correlativa_model->get_all_correlativas();

				$this->load->model('Correlativas_tipo_model');
				$data['all_correlativas_tipo'] = $this->Correlativas_tipo_model->get_all_correlativas_tipo();

                $data['_view'] = 'abm/correlativa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The correlativa you are trying to edit does not exist.');
    } 

    /*
     * Deleting correlativa
     */
    function remove($id)
    {
        $correlativa = $this->Correlativa_model->get_correlativa($id);

        // check if the correlativa exists before trying to delete it
        if(isset($correlativa['id']))
        {
            $this->Correlativa_model->delete_correlativa($id);
            redirect('correlativa/index');
        }
        else
            show_error('The correlativa you are trying to delete does not exist.');
    }
    
}
