<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Correlativas_tipo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Correlativas_tipo_model');
    } 

    /*
     * Listing of correlativas_tipo
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('correlativas_tipo/index?');
        $config['total_rows'] = $this->Correlativas_tipo_model->get_all_correlativas_tipo_count();
        $config['attributes'] = array('class' => 'page-link');
        $this->pagination->initialize($config);

        $data['correlativas_tipo'] = $this->Correlativas_tipo_model->get_all_correlativas_tipo($params);
        
        $data['_view'] = 'abm/correlativas_tipo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new correlativas_tipo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('descripcion','Descripcion','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $correlativas_tipo_id = $this->Correlativas_tipo_model->add_correlativas_tipo($params);
            redirect('correlativas_tipo/index');
        }
        else
        {            
            $data['_view'] = 'abm/correlativas_tipo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a correlativas_tipo
     */
    function edit($id)
    {   
        // check if the correlativas_tipo exists before trying to edit it
        $data['correlativas_tipo'] = $this->Correlativas_tipo_model->get_correlativas_tipo($id);
        
        if(isset($data['correlativas_tipo']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('descripcion','Descripcion','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Correlativas_tipo_model->update_correlativas_tipo($id,$params);            
                redirect('correlativas_tipo/index');
            }
            else
            {
                $data['_view'] = 'abm/correlativas_tipo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The correlativas_tipo you are trying to edit does not exist.');
    } 

    /*
     * Deleting correlativas_tipo
     */
    function remove($id)
    {
        $correlativas_tipo = $this->Correlativas_tipo_model->get_correlativas_tipo($id);

        // check if the correlativas_tipo exists before trying to delete it
        if(isset($correlativas_tipo['id']))
        {
            $this->Correlativas_tipo_model->delete_correlativas_tipo($id);
            redirect('correlativas_tipo/index');
        }
        else
            show_error('The correlativas_tipo you are trying to delete does not exist.');
    }
    
}
