<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Planes extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Planes_model');
    } 

    /*
     * Listing of planes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('planes/index?');
        $config['total_rows'] = $this->Planes_model->get_all_planes_count();
        $config['attributes'] = array('class' => 'page-link');
        $this->pagination->initialize($config);

        $data['planes'] = $this->Planes_model->get_all_planes($params);
        
        $data['_view'] = 'abm/planes/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new plane
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required');
        $this->form_validation->set_rules('duracion','Duracion','numeric|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_carrera' => $this->input->post('id_carrera'),
				'nombre' => $this->input->post('nombre'),
                'duracion' => $this->input->post('duracion'),
            );
            
            $plane_id = $this->Planes_model->add_planes($params);
            redirect('planes/index');
        }
        else
        {
			$this->load->model('Carrera_model');
			$data['all_carrera'] = $this->Carrera_model->get_all_carrera();
            
            $data['_view'] = 'abm/planes/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a plane
     */
    function edit($id)
    {   
        // check if the plane exists before trying to edit it
        $data['planes'] = $this->Planes_model->get_planes($id);
        
        if(isset($data['planes']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required');
            $this->form_validation->set_rules('duracion','Duracion','numeric|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_carrera' => $this->input->post('id_carrera'),
					'nombre' => $this->input->post('nombre'),
                    'duracion' => $this->input->post('duracion'),
                );

                $this->Planes_model->update_planes($id,$params);            
                redirect('planes/index');
            }
            else
            {
				$this->load->model('Carrera_model');
				$data['all_carrera'] = $this->Carrera_model->get_all_carrera();

                $data['_view'] = 'abm/planes/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The plane you are trying to edit does not exist.');
    } 

    /*
     * Deleting plane
     */
    function remove($id)
    {
        $plane = $this->Planes_model->get_planes($id);

        // check if the plane exists before trying to delete it
        if(isset($plane['id']))
        {
            $this->Planes_model->delete_planes($id);
            redirect('planes/index');
        }
        else
            show_error('The plane you are trying to delete does not exist.');
    }
    
}
