<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Titulo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Titulo_model');
    } 

    /*
     * Listing of titulos
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('titulo/index?');
        $config['total_rows'] = $this->Titulo_model->get_all_titulos_count();
        $config['attributes'] = array('class' => 'page-link');
        $this->pagination->initialize($config);

        $data['titulos'] = $this->Titulo_model->get_all_titulos($params);
        
        $data['_view'] = 'abm/titulo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new titulo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_plan' => $this->input->post('id_plan'),
				'id_orientacion' => $this->input->post('id_orientacion'),
				'nombre' => $this->input->post('nombre'),
            );
            
            $titulo_id = $this->Titulo_model->add_titulo($params);
            redirect('titulo/index');
        }
        else
        {
			$this->load->model('Planes_model');
			$data['all_planes'] = $this->Planes_model->get_all_planes();

			$this->load->model('Orientaciones_model');
			$data['all_orientaciones'] = $this->Orientaciones_model->get_all_orientaciones();
            
            $data['_view'] = 'abm/titulo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a titulo
     */
    function edit($id)
    {   
        // check if the titulo exists before trying to edit it
        $data['titulo'] = $this->Titulo_model->get_titulo($id);
        
        if(isset($data['titulo']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_plan' => $this->input->post('id_plan'),
					'id_orientacion' => $this->input->post('id_orientacion'),
					'nombre' => $this->input->post('nombre'),
                );

                $this->Titulo_model->update_titulo($id,$params);            
                redirect('titulo/index');
            }
            else
            {
				$this->load->model('Planes_model');
				$data['all_planes'] = $this->Planes_model->get_all_planes();

				$this->load->model('Orientaciones_model');
				$data['all_orientaciones'] = $this->Orientaciones_model->get_all_orientaciones();

                $data['_view'] = 'abm/titulo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The titulo you are trying to edit does not exist.');
    } 

    /*
     * Deleting titulo
     */
    function remove($id)
    {
        $titulo = $this->Titulo_model->get_titulo($id);

        // check if the titulo exists before trying to delete it
        if(isset($titulo['id']))
        {
            $this->Titulo_model->delete_titulo($id);
            redirect('titulo/index');
        }
        else
            show_error('The titulo you are trying to delete does not exist.');
    }
    
}
