<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ciclo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ciclo by id
     */
    function get_ciclo($id)
    {
        return $this->db->get_where('ciclos',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all ciclos count
     */
    function get_all_ciclos_count()
    {
        $this->db->from('ciclos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all ciclos
     */
    function get_all_ciclos($params = array())
    {
        $query = "SELECT c.*, p.nombre as plan, o.nombre as orientacion, ca.nombre as carrera
                  FROM ciclos c
                  INNER JOIN planes p on c.id_plan = p.id
                  INNER JOIN carrera ca on ca.id = p.id_carrera
                  LEFT JOIN orientaciones o on c.id_orientacion = o.id 
                  ORDER BY c.id desc ";

        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->query($query)->result();
    }
        
    /*
     * function to add new ciclo
     */
    function add_ciclo($params)
    {
        if (empty($params['id_orientacion'])) {
            $params['id_orientacion'] = NULL;
        }
        $this->db->insert('ciclos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ciclo
     */
    function update_ciclo($id,$params)
    {   
        if (empty($params['id_orientacion'])) {
            $params['id_orientacion'] = NULL;
        }
        $this->db->where('id',$id);
        return $this->db->update('ciclos',$params);
    }
    
    /*
     * function to delete ciclo
     */
    function delete_ciclo($id)
    {
        return $this->db->delete('ciclos',array('id'=>$id));
    }
}
