<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Orientaciones_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get orientacione by id
     */
    function get_orientaciones($id)
    {
        return $this->db->get_where('orientaciones',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all orientaciones count
     */
    function get_all_orientaciones_count()
    {
        $this->db->from('orientaciones');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all orientaciones
     */
    function get_all_orientaciones($params = array())
    {
        $query = "SELECT o.*, p.nombre as plan
                  FROM orientaciones o
                  INNER JOIN planes p on p.id = o.id_plan
                  ORDER BY id desc ";

        if(isset($params) && !empty($params))
        {
            $query.="LIMIT ".$params['limit']." OFFSET ".$params['offset']."";
        }
                
        return $this->db->query($query)->result();
    }
        
    /*
     * function to add new orientacione
     */
    function add_orientaciones($params)
    {
        $this->db->insert('orientaciones',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update orientacione
     */
    function update_orientaciones($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('orientaciones',$params);
    }
    
    /*
     * function to delete orientacione
     */
    function delete_orientaciones($id)
    {
        return $this->db->delete('orientaciones',array('id'=>$id));
    }
}
