<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Titulo extends MX_Controller{

    public $name = 'El título';
    function __construct()
    {
        parent::__construct();
        $this->load->module('template');
        $this->load->model('Titulo_model');
        $this->load->model('Planes_model');
        $this->load->model('Orientaciones_model');
        $this->load->add_package_path(APPPATH.'third_party/ion_auth/');
        $this->load->library(array('ion_auth', 'form_validation'));
        $this->load->helper(array('language'));
        $this->form_validation->set_error_delimiters($this->config->item('error_start_delimiter', 'ion_auth'), $this->config->item('error_end_delimiter', 'ion_auth'));
        $this->lang->load('auth');
    } 

    /*
     * Listing of titulos
     */
    function index()
    {

        if (!$this->ion_auth->logged_in())
        {
            redirect('login', 'refresh');
        }else {
            $params = $this->template->get_params();
            $config = $this->template->get_config('abm/titulo/index?', $this->Titulo_model->get_all_titulos_count());
            $this->pagination->initialize($config);

            $data['titulos'] = $this->Titulo_model->get_all_titulos($params);
            $data['user'] = $this->ion_auth->user()->row();
            
            if (isset($mensaje)) {
                $data['alerta'] = $mensaje;
            }
            
            $this->template->cargar_vista('abm/titulo/index', $data);
        }
    }

    /*
     * Adding a new titulo
     */
    function add()
    {   
		$this->form_validation->set_rules('nombre','Nombre','required');
        
        if($this->form_validation->run())     
        {   
            $params = array(
                'id_plan' => $this->input->post('id_plan'),
                'id_orientacion' => $this->input->post('id_orientacion'),
                'nombre' => $this->input->post('nombre'),
            );
            
            if ($this->Titulo_model->add_titulo($params))
                    $mensaje =  $this->template->cargar_alerta('success', lang('record_success'), 
                                sprintf(lang('record_add_success_text'), $this->name));    
            else   
                    $mensaje = $this->template->cargar_alerta('danger', lang('record_error'),
                                sprintf(lang('record_add_error_text'), $this->name)); 
                    
            $this->index($mensaje);
        }
        else
        {
            $data['planes'] = $this->Planes_model->get_all_planes();
            $data['orientaciones'] = $this->Orientaciones_model->get_all_orientaciones(); var_dump($data); exit();
            
            $this->template->cargar_vista('abm/titulo/add', $data);
        }
    }  

    /*
     * Editing a titulo
     */
    function edit($id)
    {   
        // check if the titulo exists before trying to edit it
        $data['titulo'] = $this->Titulo_model->get_titulo($id);
        
        if(isset($data['titulo']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_plan' => $this->input->post('id_plan'),
					'id_orientacion' => $this->input->post('id_orientacion'),
					'nombre' => $this->input->post('nombre'),
                );

                $this->Titulo_model->update_titulo($id,$params);            
                redirect('titulo/index');
            }
            else
            {
				$this->load->model('Planes_model');
				$data['all_planes'] = $this->Planes_model->get_all_planes();

				$this->load->model('Orientaciones_model');
				$data['all_orientaciones'] = $this->Orientaciones_model->get_all_orientaciones();

                $data['_view'] = 'abm/titulo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The titulo you are trying to edit does not exist.');
    } 

    /*
     * Deleting titulo
     */
    function remove($id)
    {
        $titulo = $this->Titulo_model->get_titulo($id);

        // check if the titulo exists before trying to delete it
        if(isset($titulo['id']))
        {
            $this->Titulo_model->delete_titulo($id);
            redirect('titulo/index');
        }
        else
            show_error('The titulo you are trying to delete does not exist.');
    }
    
}
