<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ciclo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ciclo by id
     */
    function get_ciclo($id)
    {
        return $this->db->get_where('ciclos',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all ciclos count
     */
    function get_all_ciclos_count()
    {
        $this->db->from('ciclos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all ciclos
     */
    function get_all_ciclos($params = array())
    {
        $query = "SELECT c.*, p.nombre as plan, o.nombre as orientacion
                  FROM ciclos c
                  INNER JOIN planes p on p.id = c.id_plan
                  LEFT JOIN orientaciones o on o.id = c.id_orientacion
                  ORDER BY id desc ";

        if(isset($params) && !empty($params))
        {
            $query.="LIMIT ".$params['limit']." OFFSET ".$params['offset']."";
        }
                
        return $this->db->query($query)->result_array();
    }
        
    /*
     * function to add new ciclo
     */
    function add_ciclo($params)
    {
        $this->db->insert('ciclos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ciclo
     */
    function update_ciclo($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('ciclos',$params);
    }
    
    /*
     * function to delete ciclo
     */
    function delete_ciclo($id)
    {
        return $this->db->delete('ciclos',array('id'=>$id));
    }
}
